# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80a4ba8f4b54a8b7f2db36011a5f5bc0d7c66064791061747d5730b7e7bbbec95b1ffc3f3c2da0449666b151bb0d14a512a12b87bf3b878fe368516d5e33fae8

test:
  secret_key_base: 23d6e238ff29db72d39ab6ab088985ac8a2dd8d35072bb2d4a139fd8ae064c2ddc36735e52145b0a63322d94e4745488310379f71d094af40ff023a194dc9fb4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
